INSERT INTO Country (name, alphacode) values('Afghanistan', 'AFG');
INSERT INTO Country (name, alphacode) values('Albania', 'ALB');
INSERT INTO Country (name, alphacode) values('Algeria', 'DZA');
INSERT INTO Country (name, alphacode) values('Andorra', 'AND');
INSERT INTO Country (name, alphacode) values('Angola', 'AGO');
INSERT INTO Country (name, alphacode) values('Argentina', 'ARG');
INSERT INTO Country (name, alphacode) values('Armenia', 'ARM');
INSERT INTO Country (name, alphacode) values('Australia', 'AUS');
INSERT INTO Country (name, alphacode) values('Austria', 'AUT');
INSERT INTO Country (name, alphacode) values('Azerbaijan', 'AZE');
INSERT INTO Country (name, alphacode) values('Bahamas', 'BHS');
INSERT INTO Country (name, alphacode) values('Bahrain', 'BHR');
INSERT INTO Country (name, alphacode) values('Bangladesh', 'BGD');
INSERT INTO Country (name, alphacode) values('Barbados', 'BRB');
INSERT INTO Country (name, alphacode) values('Belarus', 'BLR');
INSERT INTO Country (name, alphacode) values('Belgium', 'BEL');
INSERT INTO Country (name, alphacode) values('Bhutan', 'BTN');
INSERT INTO Country (name, alphacode) values('Bolivia', 'BOL');
INSERT INTO Country (name, alphacode) values('Bosnia and Herzegovina', 'BIH');
INSERT INTO Country (name, alphacode) values('Botswana', 'BWA');
INSERT INTO Country (name, alphacode) values('Brazil', 'BRA');
INSERT INTO Country (name, alphacode) values('Brunei Darussalam', 'BRN');
INSERT INTO Country (name, alphacode) values('Bulgaria', 'BGR');
INSERT INTO Country (name, alphacode) values('Burkina Faso', 'BFA');
INSERT INTO Country (name, alphacode) values('Burundi', 'BDI');
INSERT INTO Country (name, alphacode) values('Cambodia', 'KHM');
INSERT INTO Country (name, alphacode) values('Cameroon', 'CMR');
INSERT INTO Country (name, alphacode) values('Canada', 'CAN');
INSERT INTO Country (name, alphacode) values('Cape Verde', 'CPV');
INSERT INTO Country (name, alphacode) values('Central African Republic', 'CAF');
INSERT INTO Country (name, alphacode) values('Chile', 'CHL');
INSERT INTO Country (name, alphacode) values('China', 'CHN');
INSERT INTO Country (name, alphacode) values('Colombia', 'COL');
INSERT INTO Country (name, alphacode) values('Comoros', 'COM');
INSERT INTO Country (name, alphacode) values('Costa Rica', 'CRI');
INSERT INTO Country (name, alphacode) values('Croatia', 'HRV');
INSERT INTO Country (name, alphacode) values('Cuba', 'CUB');
INSERT INTO Country (name, alphacode) values('Cyprus', 'CYP');
INSERT INTO Country (name, alphacode) values('Czech Republic', 'CZE');
INSERT INTO Country (name, alphacode) values('Denmark', 'DNK');
INSERT INTO Country (name, alphacode) values('Djibouti', 'DJI');
INSERT INTO Country (name, alphacode) values('Dominican Republic', 'DOM');
INSERT INTO Country (name, alphacode) values('Ecuador', 'ECU');
INSERT INTO Country (name, alphacode) values('Egypt', 'EGY');
INSERT INTO Country (name, alphacode) values('El Salvador', 'SLV');
INSERT INTO Country (name, alphacode) values('England', 'GBR');
INSERT INTO Country (name, alphacode) values('Eritrea', 'ERI');
INSERT INTO Country (name, alphacode) values('Estonia', 'EST');
INSERT INTO Country (name, alphacode) values('Eswatini', 'SZ');
INSERT INTO Country (name, alphacode) values('Ethiopia', 'ETH');
INSERT INTO Country (name, alphacode) values('Faroe Islands', 'FRO');
INSERT INTO Country (name, alphacode) values('Fiji', 'FJI');
INSERT INTO Country (name, alphacode) values('Finland', 'FIN');
INSERT INTO Country (name, alphacode) values('France', 'FRA');
INSERT INTO Country (name, alphacode) values('Gabon', 'GAB');
INSERT INTO Country (name, alphacode) values('Gambia', 'GMB');
INSERT INTO Country (name, alphacode) values('Georgia', 'GEO');
INSERT INTO Country (name, alphacode) values('Germany', 'DEU');
INSERT INTO Country (name, alphacode) values('Ghana', 'GHA');
INSERT INTO Country (name, alphacode) values('Greece', 'GRC');
INSERT INTO Country (name, alphacode) values('Guam', 'GUM');
INSERT INTO Country (name, alphacode) values('Guatemala', 'GTM');
INSERT INTO Country (name, alphacode) values('Guernsey', 'GGY');
INSERT INTO Country (name, alphacode) values('Guyana', 'GUY');
INSERT INTO Country (name, alphacode) values('Haiti', 'HTI');
INSERT INTO Country (name, alphacode) values('Honduras', 'HND');
INSERT INTO Country (name, alphacode) values('Hungary', 'HUN');
INSERT INTO Country (name, alphacode) values('Iceland', 'ISL');
INSERT INTO Country (name, alphacode) values('India', 'IND');
INSERT INTO Country (name, alphacode) values('Indonesia', 'IDN');
INSERT INTO Country (name, alphacode) values('Iran, Islamic Republic of', 'IRN');
INSERT INTO Country (name, alphacode) values('Iraq', 'IRQ');
INSERT INTO Country (name, alphacode) values('Ireland', 'IRL');
INSERT INTO Country (name, alphacode) values('Israel', 'ISR');
INSERT INTO Country (name, alphacode) values('Italy', 'ITA');
INSERT INTO Country (name, alphacode) values('Jamaica', 'JAM');
INSERT INTO Country (name, alphacode) values('Japan', 'JPN');
INSERT INTO Country (name, alphacode) values('Jersey', 'JEY');
INSERT INTO Country (name, alphacode) values('Jordan', 'JOR');
INSERT INTO Country (name, alphacode) values('Kazakhstan', 'KAZ');
INSERT INTO Country (name, alphacode) values('Kenya', 'KEN');
INSERT INTO Country (name, alphacode) values('Kiribati', 'XXK');
INSERT INTO Country (name, alphacode) values('Kuwait', 'KWT');
INSERT INTO Country (name, alphacode) values('Kyrgyzstan', 'KGZ');
INSERT INTO Country (name, alphacode) values('Lao PDR', 'LAO');
INSERT INTO Country (name, alphacode) values('Latvia', 'LVA');
INSERT INTO Country (name, alphacode) values('Lebanon', 'LBN');
INSERT INTO Country (name, alphacode) values('Lesotho', 'LSO');
INSERT INTO Country (name, alphacode) values('Liberia', 'LBR');
INSERT INTO Country (name, alphacode) values('Libya', 'LBY');
INSERT INTO Country (name, alphacode) values('Liechtenstein', 'LIE');
INSERT INTO Country (name, alphacode) values('Lithuania', 'LTU');
INSERT INTO Country (name, alphacode) values('Luxembourg', 'LUX');
INSERT INTO Country (name, alphacode) values('Madagascar', 'MDG');
INSERT INTO Country (name, alphacode) values('Malawi', 'MWI');
INSERT INTO Country (name, alphacode) values('Malaysia', 'MYS');
INSERT INTO Country (name, alphacode) values('Maldives', 'MDV');
INSERT INTO Country (name, alphacode) values('Mali', 'MLI');
INSERT INTO Country (name, alphacode) values('Malta', 'MLT');
INSERT INTO Country (name, alphacode) values('Mauritania', 'MRT');
INSERT INTO Country (name, alphacode) values('Mauritius', 'MUS');
INSERT INTO Country (name, alphacode) values('Mexico', 'MEX');
INSERT INTO Country (name, alphacode) values('Moldova', 'MDA');
INSERT INTO Country (name, alphacode) values('Monaco', 'MCO');
INSERT INTO Country (name, alphacode) values('Mongolia', 'MNG');
INSERT INTO Country (name, alphacode) values('Montenegro', 'MNE');
INSERT INTO Country (name, alphacode) values('Morocco', 'MAR');
INSERT INTO Country (name, alphacode) values('Mozambique', 'MOZ');
INSERT INTO Country (name, alphacode) values('Myanmar', 'MMR');
INSERT INTO Country (name, alphacode) values('Namibia', 'NAM');
INSERT INTO Country (name, alphacode) values('Nauru', 'NRU');
INSERT INTO Country (name, alphacode) values('Nepal', 'NPL');
INSERT INTO Country (name, alphacode) values('Netherlands', 'NLD');
INSERT INTO Country (name, alphacode) values('Netherlands Antilles', 'ANT');
INSERT INTO Country (name, alphacode) values('New Zealand', 'NZL');
INSERT INTO Country (name, alphacode) values('Nicaragua', 'NIC');
INSERT INTO Country (name, alphacode) values('Nigeria', 'NGA');
INSERT INTO Country (name, alphacode) values('Northern Mariana Islands', 'MNP');
INSERT INTO Country (name, alphacode) values('Norway', 'NOR');
INSERT INTO Country (name, alphacode) values('Oman', 'OMN');
INSERT INTO Country (name, alphacode) values('Pakistan', 'PAK');
INSERT INTO Country (name, alphacode) values('Palau', 'PLW');
INSERT INTO Country (name, alphacode) values('Palestinian Territory', 'PSE');
INSERT INTO Country (name, alphacode) values('Panama', 'PAN');
INSERT INTO Country (name, alphacode) values('Papua New Guinea', 'PNG');
INSERT INTO Country (name, alphacode) values('Paraguay', 'PRY');
INSERT INTO Country (name, alphacode) values('Peru', 'PER');
INSERT INTO Country (name, alphacode) values('Philippines', 'PHL');
INSERT INTO Country (name, alphacode) values('Poland', 'POL');
INSERT INTO Country (name, alphacode) values('Portugal', 'PRT');
INSERT INTO Country (name, alphacode) values('Puerto Rico', 'PRI');
INSERT INTO Country (name, alphacode) values('Qatar', 'QAT');
INSERT INTO Country (name, alphacode) values('Romania', 'ROU');
INSERT INTO Country (name, alphacode) values('Russian Federation', 'RUS');
INSERT INTO Country (name, alphacode) values('Rwanda', 'RWA');
INSERT INTO Country (name, alphacode) values('San Marino', 'SMR');
INSERT INTO Country (name, alphacode) values('Sao Tome and Principe', 'STP');
INSERT INTO Country (name, alphacode) values('Saudi Arabia', 'SAU');
INSERT INTO Country (name, alphacode) values('Scotland', 'SCO');
INSERT INTO Country (name, alphacode) values('Senegal', 'SEN');
INSERT INTO Country (name, alphacode) values('Serbia', 'SRB');
INSERT INTO Country (name, alphacode) values('Seychelles', 'SYC');
INSERT INTO Country (name, alphacode) values('Sierra Leone', 'SLE');
INSERT INTO Country (name, alphacode) values('Singapore', 'SGP');
INSERT INTO Country (name, alphacode) values('Slovakia', 'SVK');
INSERT INTO Country (name, alphacode) values('Slovenia', 'SVN');
INSERT INTO Country (name, alphacode) values('Solomon Islands', 'SLB');
INSERT INTO Country (name, alphacode) values('Somalia', 'SOM');
INSERT INTO Country (name, alphacode) values('South Africa', 'ZAF');
INSERT INTO Country (name, alphacode) values('South Georgia and the South Sandwich Islands', 'SGS');
INSERT INTO Country (name, alphacode) values('South Sudan', 'SSD');
INSERT INTO Country (name, alphacode) values('Spain', 'ESP');
INSERT INTO Country (name, alphacode) values('Sri Lanka', 'LKA');
INSERT INTO Country (name, alphacode) values('Sudan', 'SDN');
INSERT INTO Country (name, alphacode) values('Suriname', 'SUR');
INSERT INTO Country (name, alphacode) values('Sweden', 'SWE');
INSERT INTO Country (name, alphacode) values('Switzerland', 'CHE');
INSERT INTO Country (name, alphacode) values('Syrian Arab Republic (Syria)', 'SYR');
INSERT INTO Country (name, alphacode) values('Tajikistan', 'TJK');
INSERT INTO Country (name, alphacode) values('Tanzania, United Republic of', 'TZA');
INSERT INTO Country (name, alphacode) values('Thailand', 'THA');
INSERT INTO Country (name, alphacode) values('Timor-Leste', 'TLS');
INSERT INTO Country (name, alphacode) values('Togo', 'TGO');
INSERT INTO Country (name, alphacode) values('Tokelau', 'TKL');
INSERT INTO Country (name, alphacode) values('Tunisia', 'TUN');
INSERT INTO Country (name, alphacode) values('Turkey', 'TUR');
INSERT INTO Country (name, alphacode) values('Turkmenistan', 'TKM');
INSERT INTO Country (name, alphacode) values('Uganda', 'UGA');
INSERT INTO Country (name, alphacode) values('Ukraine', 'UKR');
INSERT INTO Country (name, alphacode) values('United Arab Emirates', 'ARE');
INSERT INTO Country (name, alphacode) values('United States of America', 'USA');
INSERT INTO Country (name, alphacode) values('US Minor Outlying Islands', 'UMI');
INSERT INTO Country (name, alphacode) values('Uruguay', 'URY');
INSERT INTO Country (name, alphacode) values('Uzbekistan', 'UZB');
INSERT INTO Country (name, alphacode) values('Venezuela (Bolivarian Republic)', 'VEN');
INSERT INTO Country (name, alphacode) values('Viet Nam', 'VNM');
INSERT INTO Country (name, alphacode) values('Wallis and Futuna Islands', 'WLF');
INSERT INTO Country (name, alphacode) values('Yemen', 'YEM');
INSERT INTO Country (name, alphacode) values('Zambia', 'ZMB');
INSERT INTO Country (name, alphacode) values('Zimbabwe', 'ZWE');
